docker-compose-yaml: docker-compose.yml

project: drupal-example

tasks:
  pre-rollout:
    - run:
        name: drush backup
        command: drush -y ard --destination=/app/sites/default/files/private/pre-deploy.tar.gz
        service: cli

  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
    routes:
        - varnish:
            - "drupal-example.amazee.io"
